### ISSUE TITLE
Proposal: Review of priorities and development planning of `dcmqi`

### ISSUE THREAD

**Issue by fedorov** [NA-MIC/ProjectWeek#881]
### Project Description

[dcmqi](https://github.com/QIICR/dcmqi) (DICOM for Quantitative Imaging) is a free, open source C++ library for conversion between imaging research formats and the standard DICOM representation for image analysis results.

This library has been around for quite some time, and gained some adoption, but has not been actively developed for the past few years. The goal of this project would be to discuss what, if anything, could be done to make it more usable and address any of the needs that users might have. Some of the specific tasks could be:
* discuss with @jcfr any topics related to the possible integration with [ITK-Wasm dicom package](https://github.com/InsightSoftwareConsortium/itk-wasm/tree/main/packages/dicom)
* revisit basic python wrapping, similar to [pyplastimatch](https://github.com/AIM-Harvard/pyplastimatch) done by @denbonte
* clean up issue tracker
* discuss support of enhanced multiframe as SEG reference images and confirm understanding of the level of support of enhanced multiframe in Slicer/ITK (@michaelonken tried and failed to load any such images in Slicer)
* revisit documentation

**Comment by fedorov** [comment]
Related project: https://github.com/NA-MIC/ProjectWeek/pull/870

**Comment by pieper** [comment]
I think it would also make sense to discuss interoperability testing with highdicom and dcmjs and maybe other tools.

**Comment by michaelonken** [comment]
>   discuss support of enhanced multiframe as SEG reference images and confirm understanding of the level of support of enhanced multiframe in Slicer/ITK (@michaelonken tried and failed to load any such images in Slicer)

The enhanced object I tried (Enhanced CT) loaded but reported missing slice geometry; so I am not sure whether derived objects (like segmentations exported using dcmqi) will receive the correct geometry from the underlying images. Actually I had problems with the exported segmentation that's why I want to discuss this with @pieper.

 At least the part of the Slicer python code that reports the missing geometry explicity denotes that there is no support for enhanced multi-frames. On the other hand, at least Slicer displays all frames in a meaningful way and I don't know whether this comes from heuristics that kick in or parts of the Slicer code (e.g. the C++ code) that I did not look at yet.

**Comment by rfloca** [comment]
Even so I cannot join in person, I would be very interested to participate in that topic. There are some features that would greatly improve the integration and ease of utilization in MITK (potentially also other use cases and pipelines could profit). Would like to discuss that points and see how we could contribute.
One thing follows the discussion of https://github.com/QIICR/dcmqi/issues/390, but I was wondering if it makes sense to even go further and also allow to provide the information extracted from the source DCM image in a more pragmatic form (e.g. also a json). That would allow also to use dcmqi more easily in situations where you have the needed data, but not as files and people would not need to generate DCM files or learn how to populate dcmdatasets.

**Comment by fedorov** [comment]
@rfloca great to see your interest! It will be good to meet and brainstorm this together with @michaelonken. 

I do note that the [last comment](https://github.com/QIICR/dcmqi/issues/390#issuecomment-585430814) on the aforementioned issue says that you were going to submit a patch - can you update that issue with your current understanding and current understanding of the desired behavior?

**Comment by rfloca** [comment]
Yes, such a patch is already a long time on the todo list, but constantly more important things popped up (I guess you also know this problem).

I think the issue and its proposed solution is pretty much still valid. Depending on our upcoming discussion the project week it could become more of an prerequisite task. Because even if you provide a user-friendlier wrapper that e.g. allows the usage of json for communicating values, internally you most likely would still populated and DCMitem instance, I guess.

**Comment by fedorov** [comment]
Superseded by #942
